version: '2'
services:
  web:
    image: yoanndelattre/lamp:apache_php
    container_name: web
    network_mode: bridge
    hostname: web
    links:
      - "db"
    depends_on:
      - "db"
    volumes:
      - /c/Users/$USERNAME/Projet Dev:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    tty: true

  db:
    image: yoanndelattre/lamp:mysql
    container_name: db
    network_mode: bridge
    hostname: database
    ports:
      - "3306:3306"
    tty: true
