version: '3'

services:
  apache-php:
    build: Dockerfile_Apache-PHP/
    container_name: Apache-php
    ports:
      - "80:80"
      - "443:443"
    command: apt-get update && apt-get upgrade -y && service apache2 start && /bin/bash

  db:
    build: Dockerfile_MySQL-PHPMyAdmin/
    container_name: db
    ports:
      - "3306:3306"
